package com.worksyncx.hrms.enums;

public enum DocumentType {
    ID_PROOF,
    ADDRESS_PROOF,
    EDUCATION_CERTIFICATE,
    EXPERIENCE_LETTER,
    EMPLOYMENT_CONTRACT,
    OFFER_LETTER,
    RESIGNATION_LETTER,
    RELIEVING_LETTER,
    MEDICAL_CERTIFICATE,
    BANK_DETAILS,
    TAX_DOCUMENTS,
    PERFORMANCE_REVIEW,
    OTHER
}
